# -*- coding: utf-8 -*-
"""reconstruct.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ZSE673Ej-v7QEj0PAIy2tEMH8PbnYvCo
"""

import argparse
import os

import torch
import torch.nn as nn
from torchvision import datasets, transforms
from torch.utils.data import DataLoader
import matplotlib.pyplot as plt


class Autoencoder(nn.Module):
    def __init__(self, latent_dim=2):
        super(Autoencoder, self).__init__()
        self.encoder = nn.Sequential(
            nn.Flatten(),
            nn.Linear(28 * 28, 128),
            nn.ReLU(),
            nn.Linear(128, latent_dim)
        )
        self.decoder = nn.Sequential(
            nn.Linear(latent_dim, 128),
            nn.ReLU(),
            nn.Linear(128, 28 * 28),
            nn.Sigmoid()
        )

    def forward(self, x):
        z = self.encoder(x)
        out = self.decoder(z)
        out = out.view(-1, 1, 28, 28)
        return out


def save_comparison(original, reconstructed, out_path="comparison.png"):
    fig, axes = plt.subplots(1, 2, figsize=(6, 3))

    axes[0].imshow(original.squeeze(), cmap="gray")
    axes[0].set_title("Original")
    axes[0].axis("off")

    axes[1].imshow(reconstructed.squeeze(), cmap="gray")
    axes[1].set_title("Reconstructed")
    axes[1].axis("off")

    plt.tight_layout()
    plt.savefig(out_path, dpi=200, bbox_inches="tight")
    plt.close()


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--model", type=str, required=True)
    parser.add_argument("--latent_dim", type=int, required=True)
    parser.add_argument("--index", type=int, default=0)
    parser.add_argument("--output_dir", type=str, default="outputs")
    args = parser.parse_args()

    os.makedirs(args.output_dir, exist_ok=True)

    device = torch.device("cuda" if torch.cuda.is_available() else "cpu")

    transform = transforms.ToTensor()
    test_dataset = datasets.FashionMNIST(
        root="./data",
        train=False,
        download=True,
        transform=transform
    )

    sample, label = test_dataset[args.index]
    sample_input = sample.unsqueeze(0).to(device)

    model = Autoencoder(latent_dim=args.latent_dim).to(device)
    model.load_state_dict(torch.load(args.model, map_location=device))
    model.eval()

    with torch.no_grad():
        reconstructed = model(sample_input)

    original_img = sample.cpu()
    reconstructed_img = reconstructed.squeeze(0).cpu()

    original_path = os.path.join(args.output_dir, "original.png")
    reconstructed_path = os.path.join(args.output_dir, "reconstructed.png")
    comparison_path = os.path.join(args.output_dir, "comparison.png")

    plt.imsave(original_path, original_img.squeeze(), cmap="gray")
    plt.imsave(reconstructed_path, reconstructed_img.squeeze(), cmap="gray")
    save_comparison(original_img, reconstructed_img, comparison_path)

    print(f"Label index: {label}")
    print(f"Original saved to: {original_path}")
    print(f"Reconstructed saved to: {reconstructed_path}")
    print(f"Comparison saved to: {comparison_path}")


if __name__ == "__main__":
    main()